In [1]:
# 1. Create a 5×5 matrix containing numbers from 1 to 25
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)

print("5×5 Matrix:")
print(arr)

print("\nFirst Row:", end=" ")
print(arr[0])

print("\nLast Column:", end=" ")
print(arr[:, -1])

print("\nDiagonal Elements:", end=" ")
print(np.diag(arr))

5×5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First Row: [1 2 3 4 5]

Last Column: [ 5 10 15 20 25]

Diagonal Elements: [ 1  7 13 19 25]


In [2]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

B = np.array([[9, 8, 7],
              [6, 5, 4],
              [3, 2, 1]])

print("\nAddition:")
print(A + B)

print("\nSubtraction:")
print(A - B)

print("\nMatrix Multiplication:")
print(np.matmul(A, B))
# or A @ B


Addition:
[[10 10 10]
 [10 10 10]
 [10 10 10]]

Subtraction:
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]

Matrix Multiplication:
[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [3]:
import numpy as np

arr = np.arange(1, 101)

div_by_3 = arr[arr % 3 == 0]

print("No. divisible by 3:")
print(div_by_3)

No. divisible by 3:
[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [4]:
import numpy as np

arr = np.arange(1, 17).reshape(4, 4)

print("Original Matrix:")
print(arr)

arr[arr % 2 == 0] = 0

print("\nUpdated Matrix:")
print(arr)

Original Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Updated Matrix:
[[ 1  0  3  0]
 [ 5  0  7  0]
 [ 9  0 11  0]
 [13  0 15  0]]


In [5]:
import numpy as np

arr = np.random.randint(1, 100, (5, 5))

print("Random Matrix:")
print(arr)

print("\nMaximum Value:", np.max(arr))
print("Minimum Value:", np.min(arr))
print("Mean:", np.mean(arr))
print("Median:", np.median(arr))

Random Matrix:
[[43 57 21 78 86]
 [ 5 50 67 13 15]
 [26 18 44 26 66]
 [32 20 71  4 22]
 [45  4  8 46 27]]

Maximum Value: 86
Minimum Value: 4
Mean: 35.76
Median: 27.0


In [6]:
import numpy as np

arr = np.random.randint(1, 100, 20)

print("Original Array:")
print(arr)

print("\nAscending Order:")
print(np.sort(arr))

print("\nDescending Order:")
print(np.sort(arr)[::-1])

Original Array:
[94 23 88 11 93 64 77  5 61 66 42 98 17 14 35 40 82 15 35  8]

Ascending Order:
[ 5  8 11 14 15 17 23 35 35 40 42 61 64 66 77 82 88 93 94 98]

Descending Order:
[98 94 93 88 82 77 66 64 61 42 40 35 35 23 17 15 14 11  8  5]


In [7]:
import numpy as np

arr = np.arange(1, 37).reshape(6, 6)

print("Matrix:")
print(arr)

print("\nMain Diagonal:")
print(np.diag(arr))

print("\nUpper Triangular Part:")
print(np.triu(arr))

print("\nLower Triangular Part:")
print(np.tril(arr))

Matrix:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]

Main Diagonal:
[ 1  8 15 22 29 36]

Upper Triangular Part:
[[ 1  2  3  4  5  6]
 [ 0  8  9 10 11 12]
 [ 0  0 15 16 17 18]
 [ 0  0  0 22 23 24]
 [ 0  0  0  0 29 30]
 [ 0  0  0  0  0 36]]

Lower Triangular Part:
[[ 1  0  0  0  0  0]
 [ 7  8  0  0  0  0]
 [13 14 15  0  0  0]
 [19 20 21 22  0  0]
 [25 26 27 28 29  0]
 [31 32 33 34 35 36]]


In [8]:
import numpy as np

arr = np.arange(1, 21)

print("4*5 Matrix:")
print(arr.reshape(4, 5))

print("\n2*10 Matrix:")
print(arr.reshape(2, 10))

print("\n5*4 Matrix:")
print(arr.reshape(5, 4))

4*5 Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

2*10 Matrix:
[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]

5*4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [9]:
import numpy as np

arr = np.arange(1, 26).reshape(5, 5)

print("Matrix:")
print(arr)

print("\nSum of Each Row:")
print(np.sum(arr, axis=1))

print("\nSum of Each Column:")
print(np.sum(arr, axis=0))

Matrix:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Sum of Each Row:
[ 15  40  65  90 115]

Sum of Each Column:
[55 60 65 70 75]


In [10]:
import numpy as np

arr1 = np.array([1, 2, 3, 4, 5, 6, 7])
arr2 = np.array([4, 5, 6, 7, 8, 9, 10])

common = np.intersect1d(arr1, arr2)

print("Array 1:", arr1)
print("Array 2:", arr2)

print("\nCommon Elements:")
print(common)

Array 1: [1 2 3 4 5 6 7]
Array 2: [ 4  5  6  7  8  9 10]

Common Elements:
[4 5 6 7]


In [11]:
import numpy as np

arr = np.random.randint(1, 100, (5, 5))

print("Matrix:")
print(arr)

# Largest element
max_value = np.max(arr)

# Position (row, column)
position = np.unravel_index(np.argmax(arr), arr.shape)

print("\nLargest Element:", max_value)
print("Position (Row, Column):", position)

Matrix:
[[52 25 26 59 13]
 [73 43 70 83 90]
 [38 42 99 75  3]
 [43 88 72 27 63]
 [37 61 28 98 60]]

Largest Element: 99
Position (Row, Column): (np.int64(2), np.int64(2))


In [12]:
import numpy as np

marks = np.array([78, 85, 92, 67, 88, 95, 72, 81, 90, 76])

print("Student Marks:")
print(marks)

# Highest marks
highest = np.max(marks)

# Lowest marks
lowest = np.min(marks)

# Average marks
average = np.mean(marks)

# Students scoring above average
above_average = marks[marks > average]

print("\nHighest Marks:", highest)
print("Lowest Marks:", lowest)
print("Average Marks:", average)

print("\nStudents Scoring Above Average:")
print(above_average)

Student Marks:
[78 85 92 67 88 95 72 81 90 76]

Highest Marks: 95
Lowest Marks: 67
Average Marks: 82.4

Students Scoring Above Average:
[85 92 88 95 90]
